untitled/BitTorrent_app/urls.py
from django.urls import path, include
from BitTorrent_app import views

urlpatterns = [
    path('home/', views.home, name = 'home'),
    path('get_address_autom/', views.get_address_autom, name = 'get_address_autom'),
    path('files/', views.all_files, name = 'files'),
    path('dwns/', views.downloads, name = 'downloads'),
    path('uplds/', views.uploads, name = 'uploads'),
    path('updatepb/', views.update_progress_bar),
    path('', views.get_address),
    path('dt/<str:filename>/', views.download_torrent,name = 'download_torrent'),
    path('df/<str:filename>/', views.download_file,name = 'download_file'),
    path('pause/<int:dwn_id>/', views.pause_download,name = 'pause_download'),
    path('restore/<int:dwn_id>/', views.restore_download,name = 'restore_download'),
    path('cancel/<int:dwn_id>/', views.cancel_download ,name = 'cancel_download'),

]

untitled/untitled/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BitTorrent_app.urls'))
]

untitled/BitTorrent_app/models.py
from django.db import models

# Create your models here.

untitled/BitTorrent_app/forms.py
from django import forms

class AddressForm(forms.Form):
    ip = forms.GenericIPAddressField()
    port = forms.IntegerField()

    dht_ip = forms.GenericIPAddressField()
    dht_port = forms.IntegerField()

class UploadFileForm(forms.Form):
    uploaded_file = forms.FileField()

untitled/BitTorrent_app/views.py
import random
import os
import json

from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from BitTorrent_app.forms import AddressForm, UploadFileForm
from BitTorrent_app.Logic.client import Client, ClientAutom
from untitled.settings import STATICFILES_DIRS


staticfil = STATICFILES_DIRS[0]
# client = Client('127.0.0.1', 8888, staticfil + "/Storage", ("127.0.0.1", 9001))
client = None

def logged_only(func):
    global client
    def wrapper(*args,**kwargs):
        if client == None:
            return HttpResponseRedirect('/')
        return func(*args,**kwargs)
    return wrapper



@logged_only
def home(request):
    return render(request, '../templates/home.html')


@logged_only
def all_files(request):
    global client
    context = {}
    files = []
    names = []
    query = ""
    if client:
        names = client.see_files()

    if request.method == 'GET':
        query = request.GET.get('search_box', "")
        names = [f for f in names if f.find(query) != -1]

    for file in names:
        d = dict()
        d['name'] = file
        d['torrent'] = client.torrent_exists(file)
        files.append(d)
    print (files)
    context['FILES'] = files
    context['query'] = query
    return render(request, '../templates/all_files.html', context)

@logged_only
def downloads(request):
    global client
    start = 0
    context = {}
    dwns = []
    if client:
        for key in range(client.max_dwn - 1, start-1, -1):
            dwns.append({
                'id':key,
                'name': client.download[key].file_name,
                'width': round(client.download[key].actual_copy/client.download[key].size) * 100,
                'state': client.download[key].state
            })
    context['DOWNLOADS'] = dwns
    return render(request, '../templates/downloads.html', context)

@logged_only
def uploads(request):
    global client
    context = {}
    context['error'] = ''
    files = client.files
    query = ""
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['uploaded_file']._name.find('|') != -1:
                context['error'] = 'File name can not contain |'
            else:
                fd = form.cleaned_data['uploaded_file']
                name = form.cleaned_data['uploaded_file']._name
                size = form.cleaned_data['uploaded_file'].size
                # form.save()
                def copy():
                    try:
                        os.mkdir(staticfil + "/files");
                    except: pass
                    wf = open(staticfil + "/files/" + name, "wb")
                    while 1:
                        data = fd.read(50*1024*1024)
                        if len(data) == 0:
                            break
                        wf.write(data)
                    wf.close()

                    client.copy_file_from_directory(staticfil + "/files/" + name, name)
                copy()

    else:
        query = request.GET.get('search_box', "")
        files = [f for f in files if f.lower().find(query.lower()) != -1]


    form = UploadFileForm()
    context['FILES'] = files
    context['form'] = form
    context['query'] = query
    return render(request, '../templates/uploads.html', context)

@logged_only
def download_file(request, filename):
    global client
    context = {}
    if client:
       result = client.Download(filename)
    if result == 0:
        return HttpResponseRedirect('/dwns/')
    else:
        if result == 1:
            message = f'{filename} is not available at the moment'
        if result == 2:
            message = f'Download of {filename} failed'
        if result == 3:
            message = f'Download of {filename} is already in progress'
        if result == 4:
            message = f'File {filename} already exists'
        context['message'] = message
        return render(request, 'display_message.html', context)

@logged_only
def download_torrent(request, filename):
    if client:
        client.download_torrent(filename)
    return HttpResponseRedirect('/files/')


@logged_only
def update_progress_bar(request):
    global client
    history = {}
    start = 0
    history["range"] = {"first": str(start), "last": str(client.max_dwn)}
    for k in range(start, client.max_dwn):
        dwn = client.download[k]
        data = {"file": dwn.file_name, "size": dwn.size, "copy": dwn.actual_copy, "state": dwn.state}
        history[str(k)] = data

    data = {'history': history}
    if request.is_ajax():
        return JsonResponse(data)

@logged_only
def pause_download(request, dwn_id):
    global client
    client.Pause(dwn_id)
    return HttpResponseRedirect('/dwns/')


@logged_only
def restore_download(request, dwn_id):
    global client
    client.Restore(dwn_id)
    return HttpResponseRedirect('/dwns/')

def cancel_download(request, dwn_id):
    global client
    client.Cancel(dwn_id)
    return HttpResponseRedirect('/dwns/')

def get_address_autom(request):
    global client
    path = staticfil + "/Storage"
    client = ClientAutom(path)
    return HttpResponseRedirect('/home/')

def get_address(request):
    global client
    if (client == None) and request.method == "POST":
        form = AddressForm(request.POST)
        if form.is_valid():
            path = staticfil + "/Storage"
            data = form.cleaned_data
            try:
                os.mkdir(path)
            except:
                pass
            # client = Client('192.168.43.124', 8888, path, (data['ip'], data['port']))
            client = Client(data['dht_ip'], data['dht_port'], path, (data['ip'], data['port']))
            return HttpResponseRedirect('/home/')
    elif client == None:
        form = AddressForm()
        return render(request, 'input_address.html', {'form': form})
    else:
        return HttpResponseRedirect('/home/')

untitled/templates/all_files.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block menu-bar %}
    <div class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
            <li><a href="/home">Home</a></li>
            <li class="active"><a href="/files">Files</a></li>
            <li><a href="/dwns">Downloads</a></li>
            <li><a href="/uplds">Uploads</a></li>
            <li><a href="{% static "README.pdf" %}">About</a></li>
        </ul>
    </div>
{% endblock %}

{% block body %}
    <div class=slider>
        <div class="container">
            <div class="row" style="margin-bottom: 10px">
                <div class="col-md-5">
                    <form role="form" type="get" action=".">
                        <input id="search_box" name="search_box" type="text" class="form-control search_box"
                               autocomplete="off" placeholder="Search Here" value= {{ query }}>
                    </form>
                </div>
            </div>
        </div>

        {% if FILES %}


            <div class="container">
                <div class="accordion">
                    <div class="panel-group" id="accordion1">
                        {% for file in  FILES %}

                            <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1"
                                       href="#{{ file.name|slugify }}">
                                        {{ file.name }}
                                        <i class="fa fa-angle-right pull-right"></i>
                                    </a>
                                </h3>
                            </div>

                            <div id="{{ file.name|slugify }}" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <div class="media accordion-inner">
                                        <div class="pull-left">
                                            {% if not file.torrent %}
                                                <a class="fa fa-download" href="{% url 'download_torrent' file.name %}">
                                                    Download Torrent </a>
                                                <div></div>
                                            {% endif %}
                                            <a class="fa fa-download" href="{% url 'download_file' file.name %}">
                                                Download
                                                File </a>
                                        </div>

                                        {#                                      <div class="media-body">#}
                                        {#                                        <h4>Adipisicing elit</h4>#}
                                        {#                                        <p>I Like {{ file }}</p>#}
                                        {#                                      </div>#}
                                    </div>
                                </div>
                            </div>


                        {% endfor %}
                        </div>
                    </div>
                </div>
                {#        {% if FILES %}#}
                {#            <ul class="pagination pagination-lg">#}
                {#                <li><a href="/files///0"><i class="fa fa-long-arrow-left"></i></a></li>#}
                {#                <li class="active"><a href="/files//1/0">1</a></li>#}
                {#                <li><a href="/files//2/0">2</a></li>#}
                {#                <li><a href="/files//3/0">3</a></li>#}
                {#                <li><a href="/files//4/0">4</a></li>#}
                {#                <li><a href="/files//5/0">5</a></li>#}
                {#                <li><a href="/files///1"><i class="fa fa-long-arrow-right"></i></a></li>#}
                {#            </ul>#}
                {#        {% endif %}#}
            </div>
        {% else %}
            <div class="container">
                <h2>No files to show</h2>
            </div>
        {% endif %}
    </div>


{% endblock %}

untitled/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>D&D BitTorrent</title>
    <!-- Bootstrap -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/font-awesome.min.css' %}">
    <link href="{% static '/css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static '/css/style.css' %}" rel="stylesheet">
    <link href="{% static '/css/responsive.css' %}" rel="stylesheet">
    <!-- =======================================================
      Theme Name: Gp
      Theme URL: https://bootstrapmade.com/gp-free-multipurpose-html-bootstrap-templat/
      Author: BootstrapMade
      Author URL: https://bootstrapmade.com
    ======================================================= -->

</head>

<body class="homepage">
<header id="header">
    <nav class="navbar navbar-fixed-top" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/home">D&D BitTorrent</a>
            </div>
            {% block menu-bar %}

            {% endblock %}

        </div>
        <!--/.container-->
    </nav>
    <!--/nav-->

</header>
<!--/header-->

{% block body %}

{% endblock %}


<!--/#footer-->

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
{#  <script src="{%  static '/js/jquery.min.js'%}"></script>#}
<script src="{% static '/js/jquery.js' %}"></script>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
<script src="{% static '/js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static '/js/jquery.isotope.min.js' %}"></script>
<script src="{% static '/js/wow.min.js' %}"></script>
<script src="{% static '/js/main.js' %}"></script>


{% block js %}

{% endblock %}
</body>
</html>

untitled/templates/display_message.html
{% extends 'base.html' %}

{% block body %}
    <div class=slider>
        <div class="container">
            <h3> {{ message }}</h3>
            <button> <a href="/files/">Accept </a></button>
        </div>
    </div>
{% endblock %}

untitled/templates/downloads.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block menu-bar %}
    <div class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
            <li><a href="/home">Home</a></li>
            <li><a href="/files">Files</a></li>
            <li class="active"><a href="/dwns">Downloads</a></li>
            <li><a href="/uplds">Uploads</a></li>
            <li><a href="{% static "README.pdf" %}">About</a></li>
        </ul>
    </div>
{% endblock %}

{% block body %}
    <div class=slider>
        <div class="container">
            {% if not DOWNLOADS %}
                <h2>No downloads to show</h2>
            {% endif %}
            <div class="progress-wrap">
                {% for download in DOWNLOADS %}
                    <div class="row">
                        <div class="col-md-6">
                            <h3>{{ download.name }}</h3>
                            <div class="progress">
                                <div class="progress-bar color1" role="progressbar" aria-valuenow="0" aria-valuemin="0"
                                     aria-valuemax="100" id="{{ download.id }}" style="width: {{ download.width }}%">
                                </div>
                            </div>
                        </div>
                        <div class=col-md-offset-6 style="margin-top: 40px" id="action_container">
                            {% if download.state == "fail" %}
                                <button><a class="fa fa-download" href="{% url 'restore_download' download.id %}"
                                           id="button{{ download.id }}"> Retry</a></button>
                                <button id="cancelbutton{{ download.id }}"><a class="fa fa-ban" href="{% url 'cancel_download' download.id %}"
                                           > Cancel</a></button>
                            {% endif %}
                            {% if download.state == "finish" %}
                                <button class="btn"><a class="fa fa-clipboard"
                                                       href="{% static "/Storage/" %}{{ download.name }}"
                                                       id="button{{ download.id }}"> View</a>
                                </button>
                                 <button id="cancelbutton{{ download.id }}"><a class="fa fa-ban" href="{% url 'cancel_download' download.id %}"
                                           > Cancel</a></button>

                            {% endif %}
                            {% if download.state == "ejecution" %}
                                <button><a class="fa fa-pause" href="{% url 'pause_download' download.id %}"
                                           id="button{{ download.id }}"> Pause</a></button>
                                <button id="cancelbutton{{ download.id }}"><a class="fa fa-ban" href="{% url 'cancel_download' download.id %}"
                                           > Cancel</a></button>
                            {% endif %}
                            {% if download.state == "pause" %}
                                <button><a class="fa fa-play" href="{% url 'restore_download' download.id %}"
                                           id="button{{ download.id }}"> Continue</a></button>
                                <button id="cancelbutton{{ download.id }}"><a class="fa fa-ban" href="{% url 'cancel_download' download.id %}"
                                           > Cancel</a></button>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
    <script type="text/javascript">
        $(document).ready(function () {
            const interval = setInterval(() => {
                $.ajax({
                    url: '/updatepb',
                    success: function (data) {
                        console.log("Here !!!!!!!!");
                        console.log(data);
                        console.log(data["history"]["range"]["last"]);
                        for (i = 0; i < parseInt(data["history"]["range"]["last"]); i++) {
                            console.log("iterations");
                            console.log(i);
                            bar = document.getElementById(i.toString());
                            progress = (data["history"][i.toString()]["copy"] / data["history"][i.toString()]["size"]) * 100
                            console.log(progress);
                            bar.style.width = progress.toFixed(0) + '%';
                            bar.innerText = progress.toFixed(0) + '%';
                            var keep = 0;
                            if (data["history"][i.toString()]["state"] == "finish") {
                                button = document.getElementById("button".concat(i.toString()));
                                button.innerText = "View";
                                button.href = "/static/Storage/".concat(data["history"][i.toString()]["file"]);
                                button.className = "fa fa-clipboard";

                                cancelbutton = document.getElementById("cancelbutton".concat(i.toString()));
                                cancelbutton.style.display = "none";

                                bar.className = "progress-bar color2";

                            }
                            if (data["history"][i.toString()]["state"] == "fail") {
                                button = document.getElementById("button".concat(i.toString()));
                                button.innerText = "Retry";
                                button.href = "/restore/".concat(i.toString());
                                button.className = "fa fa-download";
                                bar.className = "progress-bar color4";
                            }
                            if (data["history"][i.toString()]["state"] != "fail" &&
                                data["history"][i.toString()]["state"] != "finish" &&
                                data["history"][i.toString()]["state"] != "paused"
                            ) {
                                keep = 1;
                            }
                        }
                        if (keep == 0) {
                            clearInterval(interval);
                        }

                    }
                });
            }, 1000)
        });

    </script>
{% endblock %}

untitled/templates/input_address.html
{% extends 'base.html' %}

{% block menu-bar %}
    <div class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
            <li class="active"><a href="/get_address_autom">Search</a></li>
        </ul>
    </div>
{% endblock %}

{% block body %}
    <div class=slider>
    <div class="container" align="center">
        {% if form.errors %}
            <p style="color: red;">Por favor corrige lo siguiente:
            </p>

        {% endif %}
        <form action="" method="post">{% csrf_token %}
            <table >
                <h2>Insert Address</h2>
                <tr>
                    <th><label for="id_ip">Ip:</label></th>
                    <td><input type="text" name="ip" required id="id_ip"></td>
                </tr>
                <tr>
                    <th><label for="id_port">Port:</label></th>
                    <td><input type="number" name="port" required id="id_port"></td>
                </tr>
            </table>
            <h2>Insert DHT Address</h2>
            <table>

                <tr>
                    <th><label for="id_dht_ip">Ip:</label></th>
                    <td><input type="text" name="dht_ip" required id="id_dht_ip"></td>
                </tr>
                <tr>
                    <th><label for="id_dht_port">Port:</label></th>
                    <td><input type="number" name="dht_port" required id="id_dht_port"></td>
                </tr>
            </table>
            <button type="submit" class="btn btn-primary btn-lg">Submit</button>
            {#                <input type="submit" value="Submit">#}
        </form>
    </div>
    </div>
{% endblock %}

untitled/templates/upload_file.html
{% extends 'base.html' %}

{% block menu-bar %}
    <div class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
            <li><a href="/home">Home</a></li>
            <li><a href="/files">Files</a></li>
            <li><a href="/dwns">Downloads</a></li>
            <li class="active"><a href="/uplds">Uploads</a></li>
        </ul>
    </div>v
{% endblock %}

{% block body %}
    <div class=slider>
        <div class="container">
            {#            <form method="post" enctype="multipart/form-data">#}
            {#                {% csrf_token %}#}
            {#                <input type="file" name="myfile">#}
            {#                <button type="submit">Upload</button>#}
            {#            </form>#}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Upload</button>
            </form>
        </div>
    </div>
{% endblock %}

untitled/templates/uploads.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block menu-bar %}
    <div class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
            <li><a href="/home">Home</a></li>
            <li><a href="/files">Files</a></li>
            <li><a href="/dwns">Downloads</a></li>
            <li class="active"><a href="/uplds">Uploads</a></li>
            <li><a href="{% static "README.pdf" %}">About</a></li>

        </ul>
    </div>
{% endblock %}

{% block body %}
    <div class=slider>

        <div class="container">
            <div class="row" style="margin-bottom: 10px">
                <div class="col-md-5">
                    <form role="form" type="get" action=".">
                        <input id="search_box" name="search_box" type="text" class="form-control search_box"
                               autocomplete="off" placeholder="Search Here" value= {{ query }}>
                    </form>
                </div>
            </div>
            <div class="row" style="margin-bottom: 20px ; margin-left: 2px">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p><label for="id_uploaded_file">Select file to upload:</label> <input type="file"
                                                                                           name="uploaded_file"
                                                                                           required
                                                                                           id="id_uploaded_file">
                    </p>
                    <button type="submit">Upload File</button>
                </form>
                {% if error %}
                    <p> {{ error }} </p>
                {% endif %}
                {#                <a class="btn btn-primary col"  href="{% url 'upload_file' %}"> Upload File</a>#}
            </div>

        </div>
        {% if FILES %}

            <div class="container">
            <div class="accordion">
                <div class="panel-group" id="accordion1">
                    {% for file in  FILES %}

                        <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1"
                                   href="#{{ file|slugify }}">
                                    {{ file }}
                                    <i class="fa fa-angle-right pull-right"></i>
                                </a>
                            </h3>
                        </div>

                        <div id="{{ file|slugify }}" class="panel-collapse collapse">
                            <div class="panel-body">
                                <div class="media accordion-inner">
                                    <div class="pull-left">
                                        <a class="fa fa-eye" href="{% static "/Storage/" %}{{ file }}"> View</a>
                                    </div>
                                </div>
                            </div>
                        </div>


                    {% endfor %}
                    </div>
                </div>
            </div>
            {#        {% if FILES %}#}
            {#        <ul class="pagination pagination-lg">#}
            {#            <li><a href="#"><i class="fa fa-long-arrow-left"></i></a></li>#}
            {#            <li class="active"><a href="#">1</a></li>#}
            {#            <li><a href="#">2</a></li>#}
            {#            <li><a href="#">3</a></li>#}
            {#            <li><a href="#">4</a></li>#}
            {#            <li><a href="#">5</a></li>#}
            {#            <li><a href="#"><i class="fa fa-long-arrow-right"></i></a></li>#}
            {#        </ul>#}
            {#        {% endif %}#}
        {% else %}
            <div class="container">
                <h2>No files to show</h2>
            </div>
        {% endif %}
        </div>


    </div>
{% endblock %}